export const mockJobs = [
  {
    id: "1",
    title: "Desenvolvedor Frontend Senior",
    company: "TechCorp Brasil",
    location: "São Paulo, SP",
    type: "Home Office",
    area: "Tecnologia",
    level: "Sênior",
    date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    description: "Buscamos um desenvolvedor frontend com forte experiência em React, TypeScript e arquitetura de micro-frontends.",
    url: "https://example.com/job/1"
  },
  {
    id: "2",
    title: "Analista de Marketing Digital Júnior",
    company: "Creative Ads",
    location: "Rio de Janeiro, RJ",
    type: "Presencial",
    area: "Marketing",
    level: "Júnior",
    date: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    description: "Planejar e executar campanhas de performance no Google Ads e Meta Ads.",
    url: "https://example.com/job/2"
  },
  {
    id: "3",
    title: "Engenheiro de Dados Pleno",
    company: "DataOps Solutions",
    location: "Belo Horizonte, MG",
    type: "Híbrido",
    area: "Tecnologia",
    level: "Pleno",
    date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    description: "Experiência com Apache Spark, Python e AWS (S3, Redshift, EMR).",
    url: "https://example.com/job/3"
  },
  {
    id: "4",
    title: "Desenvolvedor Backend (Node.js)",
    company: "FintechX",
    location: "São Paulo, SP",
    type: "Home Office",
    area: "Tecnologia",
    level: "Pleno",
    date: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    description: "Desenvolver APIs escaláveis para nossa nova plataforma de pagamentos utilizando Node.js e PostgreSQL.",
    url: "https://example.com/job/4"
  },
  {
    id: "5",
    title: "Gerente de Projetos Senior",
    company: "BuildIt Construtora",
    location: "Curitiba, PR",
    type: "Presencial",
    area: "Engenharia",
    level: "Sênior",
    date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    description: "Gerenciar projetos de construção civil do início ao fim, garantindo prazos e orçamentos.",
    url: "https://example.com/job/5"
  },
  {
    id: "6",
    title: "Estágio em SEO",
    company: "WebBoost",
    location: "Florianópolis, SC",
    type: "Home Office",
    area: "Marketing",
    level: "Estágio",
    date: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    description: "Otimização de sites para motores de busca, análise de concorrência e link building.",
    url: "https://example.com/job/6"
  },
  {
    id: "7",
    title: "Enfermeiro(a) Chefe",
    company: "Hospital Central",
    location: "Porto Alegre, RS",
    type: "Presencial",
    area: "Saúde",
    level: "Sênior",
    date: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    description: "Supervisão da equipe de enfermagem do turno da noite na UTI.",
    url: "https://example.com/job/7"
  },
  {
    id: "8",
    title: "UX/UI Designer Júnior",
    company: "DesignHub",
    location: "São Paulo, SP",
    type: "Híbrido",
    area: "Design",
    level: "Júnior",
    date: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    description: "Criar interfaces incríveis e intuitivas para aplicativos web e mobile usando Figma.",
    url: "https://example.com/job/8"
  },
  {
    id: "9",
    title: "Advogado Societário Pleno",
    company: "Lopes & Silva Advogados",
    location: "Rio de Janeiro, RJ",
    type: "Presencial",
    area: "Jurídico",
    level: "Pleno",
    date: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    description: "Elaboração de contratos sociais, atas e assessoria em M&A.",
    url: "https://example.com/job/9"
  },
  {
    id: "10",
    title: "Desenvolvedor Mobile (React Native)",
    company: "AppStoreBR",
    location: "Campinas, SP",
    type: "Home Office",
    area: "Tecnologia",
    level: "Pleno",
    date: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    description: "Desenvolver nosso app principal para iOS e Android. Experiência com Redux e hooks é essencial.",
    url: "https://example.com/job/10"
  }
];
